### ISSUE TITLE
Library not published in PyPi

### ISSUE THREAD

**Issue by tdmb** [bbc/rd-apmm-python-lib-rtp#6]
Could you release this library and publish it in PyPi? Thanks!

**Comment by j616** [comment]
Hello. Sorry for the slow response. Seems this got lost in the sea of GitHub notifications at some point. I've added a ticket to the backlog to modify the CI to upload to PyPi. I'll hopefully get to it soon and will let you know when I've done it.

**Comment by j616** [comment]
This lib is now available at https://pypi.org/project/rtp/

**Comment by tdmb** [comment]
Thanks!
